import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d


# COMMENTS ON OUTPUTS GIVEN IN THIS SCRIPT


# -------------Testing the C random number generator---------------------------


# Loading the data into x,y,z arrays
data = np.loadtxt('rand_points.txt')
x = data[:,0]
y = data[:,1]
z = data[:,2]

print(len(x), len(y), len(z))

fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(x, y, z, marker='.', cmap='Greens')  # making a 3D plot
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

# The 3D random distributions can be seen in "PS7_Q1_C_gen.png",.......
#.... "PS7_Q1_C_gen_angle1.png" and "PS7_Q1_C_gen_angle2.png".
# When looking from and angle where the X and Z axes are facing us directly,...
#....several planes can be seen in the 3D distribution, tilting towards the Z axis.
# This shows that the random numbers generated by the C generator are not....
#.... entirely random, but rather have a pattern. There are about 32 planes.


# ---------------Python Random number generator from here-----------------------


n = 100000000
length = 400

# Initially we test random numbers between 0 and 1 via random.rand

coordinates = np.random.rand(100, 100, 100)
x = coordinates[:,0]
y = coordinates[:,1]
z = coordinates[:,2]

print(len(x))

fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(x, y, z, marker='.', cmap='Greens')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

# Then we test for random numbers via the randint method.

coordinates = np.random.randint(n, size=(length, length, length))
x = coordinates[:,0]
y = coordinates[:,1]
z = coordinates[:,2]

fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(x, y, z, marker='.', cmap='Greens')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

# The figures from the two random number generators can be seen in....
#.... "PS7_Q1_Py_gen_1.png" and "PS7_Q1_Py_gen_2.png" which shows the 3D plots..
#....of the random scatter from Python.
# No planes could be detected in either of the two 3D plots.
# This shows that the Python generated random numbers are truly random as ....
#.... opposed to the C random number generator. 

    
